spring.application.name=AccountTransferTask


# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt.secret=2XZCFnmx0gac6Obn7LVsXtxpT36eCKJBGEbXg3luFuN2
jwt.expiration=360000